# Generated by Django 3.1.12 on 2025-10-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_income', models.FloatField()),
                ('food', models.FloatField(default=0)),
                ('travel', models.FloatField(default=0)),
                ('medical', models.FloatField(default=0)),
                ('others', models.FloatField(default=0)),
                ('total_expense', models.FloatField(default=0)),
                ('predicted_status', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
